version: '3.4'
services:
  gui:
    image: ghcr.io/verapdf/verapdf_gui:latest
    depends_on:
      - file-storage
      - job-service
      - worker
    ports:
      - ${GUI_PORT:-80}:80
    restart: always
